/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#f7f9fc",
        "surface-bright": "#f7f9fc",
        "surface-container-low": "#f2f4f7",
        "surface-container": "#eceef1",
        "surface-container-high": "#e6e8eb",
        "surface-container-highest": "#e0e3e6",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d8dadd",
        "surface-variant": "#e0e3e6",
        primary: "#002b22",
        "primary-container": "#004336",
        "on-primary": "#ffffff",
        "on-primary-container": "#12b99a",
        "primary-fixed": "#6ff9d6",
        "primary-fixed-dim": "#4eddbb",
        "on-primary-fixed": "#002019",
        "on-primary-fixed-variant": "#005141",
        "inverse-primary": "#4eddbb",
        secondary: "#386188",
        "secondary-container": "#aad3ff",
        "on-secondary-container": "#315b81",
        "secondary-fixed": "#cfe5ff",
        "secondary-fixed-dim": "#a2caf7",
        "on-secondary-fixed": "#001d34",
        "on-secondary-fixed-variant": "#1d496f",
        "on-secondary": "#ffffff",
        tertiary: "#530001",
        "tertiary-container": "#7c0002",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-surface": "#191c1e",
        "on-surface-variant": "#42474e",
        "on-background": "#191c1e",
        outline: "#72777f",
        "outline-variant": "#c2c7cf",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f4",
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      boxShadow: {
        premium: "0 12px 32px rgba(0, 43, 34, 0.06)",
      },
    },
  },
  plugins: [],
}
